modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://my.issue.tracker/" #optional
license="GPL License"
[[mods]] #mandatory
modId="refinable_resources" #mandatory
version="0.51" #mandatory
displayName="Refinable Resources" #mandatory
logoFile="examplemod.png" #optional
credits="Kathairis Development Team" #optional
authors="Krevik" #optional
description='''
Simple mod that allows you to refine all the resources in the game.
'''